algo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
from django.conf.urls.static import static
from django_summernote import urls as summernote_urls

urlpatterns = [
    path("i18n/", include("django.conf.urls.i18n")),

]


urlpatterns += i18n_patterns (
    path('admin/', admin.site.urls),
    path('', include('product.urls')),
    path('', include('users.urls')),
    path('summernote/', include('django_summernote.urls')),
    

)


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views as auth_view
from django.contrib.auth.decorators import login_required
from django.utils.translation import gettext as _
from django.contrib.auth.views import LoginView, LogoutView
from django.views.i18n import set_language


urlpatterns = [
    path('user/<slug:slug>', ProfileView.as_view(), name='profile'),
    path('set-language/', set_language, name='set_language'),
    
    path('profile/update/<int:id>/', login_required(ProfileUpdate), name='profile_update'),
    path('user/update/info/', login_required(user_update_info), name='user_update_info'),
    path('accounts/register', register, name='register',),
    path('accounts/login/', login_view, name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('settings',  settings, name='settings'),
    path('accounts/change/password/', login_required(change_password), name='change_password'),
    path('reset_passaword/', auth_view.PasswordResetView.as_view(template_name='password_reset/reset_password.html',
     title=_('Forgot Password'),
     success_url = reverse_lazy('password_reset_done_new')), name='reset_password'),
    path('reset_passaword_sent/', posword_reset_done, name='password_reset_done_new'),
    path('accounts/reset/<uidb64>/<token>/', auth_view.PasswordResetConfirmView.as_view(template_name='password_reset/password_reset_confirm.html', success_url = reverse_lazy('passaword_reset_complet_new')), name='password_reset_confirm'),
    path('reset_passaword_complet/', auth_view.PasswordResetCompleteView.as_view(template_name='password_reset/reset_done.html'), name='passaword_reset_complet_new'),

 
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _
from django.utils.text import slugify
from django.utils.crypto import get_random_string



class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, blank=True)
    avatar = models.ImageField(upload_to='avatar/', default='user_default.webp', blank=True)
    phone = models.IntegerField(blank=True, default=False)
    country = models.CharField(max_length=40, blank=True)
    blocked = models.BooleanField(default=False, blank=True)
    update = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    last_visit = models.DateTimeField(auto_now=True)
    verificated = models.BooleanField(default=False)
    slug = models.SlugField(blank=True, null=True)
    

    def __str__(self):
        return f"{self.user.first_name} {self.user.last_name} - {self.created.strftime('%d-%m-%Y')}"

    
    def save(self, *args, **kwargs):
        self.slug = slugify(str(self.user.username))
        return super().save(*args, **kwargs)
    
    def get_absolute_url(self):
        return f'/{self.slug}'

users/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm
from django.contrib.auth.models import User
from .models import Profile
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

    
    def clean_username(self):
        cd = self.cleaned_data
        if not User.objects.filter(username=cd['username']).exists():
            raise ValidationError(_("Il n'y a pas d'utilisateur enregistré avec ce nom !"))
        return cd['username']




class SignUpForm(forms.ModelForm):
    email = forms.EmailField()
    first_name = forms.CharField(max_length=50)
    last_name = forms.CharField(max_length=50)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password')



class UserCreationForm(forms.ModelForm):
    username = forms.CharField(label=_("Nom d'utilisateur"), max_length=30,help_text=_("Le nom d'utilisateur ne doit pas contenir d'espaces"),
         widget=forms.TextInput(attrs={'class': 'form-control input-size bg-secondary', 'placeholder': _("Nom d'utilisateur")}))
    username = forms.CharField(label=_("Nom d'utilisateur"), max_length=30,help_text=_("Le nom d'utilisateur ne doit pas contenir d'espaces"), widget=forms.TextInput(
        attrs={'class': 'form-control input-size', 'placeholder': _("Nom d'utilisateur")}))
    email = forms.EmailField(label=_('Email'), widget=forms.EmailInput(
        attrs={'class': 'form-control', 'placeholder': _('Email')}))
    first_name = forms.CharField(label=_('Prénom'), widget=forms.TextInput(
        attrs={'class': 'form-control input-size', 'placeholder': _('Prénom')}))
    last_name = forms.CharField(label=_('Nome'),widget=forms.TextInput(
        attrs={'class': 'form-control input-size ', 'placeholder': _('Nome')}))
    password1 = forms.CharField(label=_('Password'), widget=forms.PasswordInput(
        attrs={'class': 'form-control input-size', 'placeholder': _('Password')}), min_length=8)
    password2 = forms.CharField(label=_('Confirm Password'), widget=forms.PasswordInput(
        attrs={'class': 'form-control input-size', 'placeholder': _('Confirm Password')}), min_length=8)

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'password1', 'password2')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password1'] != cd['password2']:
            raise ValidationError(_('Le mot de passe ne correspond pas.'))
        return cd['password2']

    def clean_username(self):
        cd = self.cleaned_data
        if User.objects.filter(username=cd['username']).exists():
            raise ValidationError(_('Il y a un utilisateur enregistré avec ce nom !'))
        return cd['username']



    def clean_email(self):
        cd = self.cleaned_data
        if User.objects.filter(email=cd['email']).exists():
            raise ValidationError(_("Il y a un utilisateur enregistré avec cet e-mail !"))
        return cd['email']    




class UpdateProfile(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('avatar', 'phone', 'country' )


class UserUpdateInfo(UserChangeForm):
    email = forms.EmailField()
    first_name = forms.CharField(max_length=50)
    last_name = forms.CharField(max_length=50)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')
    


class PasswordChange(PasswordChangeForm):
    old_password = forms.CharField(widget=forms.PasswordInput)
    new_password1 = forms.CharField(widget=forms.PasswordInput)
    new_password2 = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('old_password', 'new_password1', 'new_password2')

    def clean(self):
        cleaned_data = super(PasswordChange, self).clean()
        if 'password1' in self.cleaned_data and 'password2' in self.cleaned_data:
            if self.cleaned_data['password1'] != self.cleaned_data['password2']:
                raise forms.ValidationError(_('The two passwords did not match'))
        return cleaned_data

users/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Profile
from django.views.generic import DetailView, UpdateView, UpdateView
from .forms import *
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash



def login_view(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            if user.is_superuser:
                return redirect('/dash')
            else:
                return redirect('home')
        else:
            return render(request, 'registrations/login.html', {'error': 'Authentification invalide'})
    else:
        return render(request, 'registrations/login.html')
    

# REGISTER 
def register(request):
    if request.user.is_authenticated:
        return redirect('home')
    else:
        form = UserCreationForm()
        if request.method == 'POST':
            form = UserCreationForm(request.POST)
            if form.is_valid():
                new_user = form.save(commit=False)
                form.cleaned_data['username']
                new_user.email
                new_user.save()
                if new_user is not None:
                    if new_user.is_active:
                        login(request, new_user)
                        return redirect('home')
                    
                return redirect('login')
    context = {'title': _('Register'), 'form': form, }
    return render(request, 'registrations/register.html', context)


class ProfileView(DetailView):
    model = Profile
    template_name = 'profile/profile.html'
    count_hit = True

    def get_context_data(self, *arge, **kwargs):
        context = super(ProfileView, self).get_context_data(*arge, **kwargs)
        page = get_object_or_404(Profile, slug=self.kwargs['slug'])
        title = f'{page.user.first_name} {page.user.last_name}'
        description = _('You can join now to connect with your  friends and enjoy your books and courses register now')
        context["page"] = page
        context['description'] = f'{title} {description}'
        return context




def ProfileUpdate(request, id):
    profile = get_object_or_404(Profile, id=id)
    form = UpdateProfile(instance=profile)
    if request.method == "POST":
        if request.user == profile.user:
            form = UpdateProfile(request.POST, instance=request.user.profile, files=request.FILES)
            if form.is_valid():
                form.save()
                messages.success(request, 'Your profile has been updated!')
                return redirect('profile_update', id=profile.id)
        else:
            return redirect('/')
        

    context = {
        'page': profile,
        'title': _('Update Profile')
    }

    return render(request, 'profile/update_profile.html', context)


class ProfileViewUpdate(UpdateView):
    model = Profile
    template_name = 'profile/update_profile.html'
    form_class = UpdateProfile

    def get_context_data(self, *arge, **kwargs):
        context = super(ProfileViewUpdate, self).get_context_data(*arge, **kwargs)
        page = get_object_or_404(Profile, id=self.kwargs['pk'])
        title = _('Update Profile')
        context["page"] = page
        context["title"] = title
        return context
    

def user_update_info(request):
    confirm = False
    if request.method == 'POST':
        form = UserUpdateInfo(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            confirm = True
    else:
        form = UserUpdateInfo(instance=request.user)
    context = {'form': form, 'confirm':confirm, 'title': _("Contact information")}
    return render(request, 'profile/user_update_info.html', context)


def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was successfully updated!')
            return redirect('change_password')
        else:
            messages.error(request, 'Please correct the errors below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'profile/change-password.html', {'form': form})





def posword_reset_done(request):
    context = {'title':_("Password reset has been sent")}
    return render(request, 'password_reset/reset_password_done.html', context)


def settings(request):
    return render(request, 'settings.html')


        

users/templates/profile/change-password.html
{% extends 'dash.html' %}
{% load static %}
{% load i18n %}


{% block content %}
<div class="container">
    <div class="row d-flex justify-content-center">
        <div class='col-md-6'>
            <h1 class="h4">{% trans "Change Password" %}</h1>
            <form action="" method="POST">
                {% csrf_token %}
                <label class="p-0" for="id_old_password" >{% trans 'Old Password' %}</label><br>
                {% if form.old_password.errors %}
                <span class="helptext text-danger">{% trans 'The old password is incorrect.' %}</span>
                {% endif %}
                <input type="password" class="form-control border" name="old_password" autocomplete="current-password" autofocus required id="id_old_password"><br>
                <label class="p-0" for="id_new_password1">{% trans 'New password' %}</label><br>
                <input type="password" class="form-control border" name="new_password1" autocomplete="new-password" required id="id_new_password1"><br>
                <span class="helptext"></span>
                <label class="p-0" for="id_new_password2">{% trans 'New Password confirmation' %}</label><br>
                {% if form.new_password2.errors %}
                <span class="helptext text-danger">{% trans 'Le mot de passe ne correspond pas.' %}</span>
                {% endif %}
                <input type="password" class="form-control border" name="new_password2" autocomplete="new-password" required id="id_new_password2"><br>
                <button type="submit" class="btn btn-success mt-3 w-100">{% trans 'Change' %}</button>
            </form>
            <br>
            <div>
                <ul class="p-0">
                    <li> {% trans 'Your password can’t be too similar to your other personal information.' %} </li>
                    <li> {% trans 'Your password must contain at least 8 characters.' %} </li>
                    <li> {% trans 'Your password can’t be a commonly used password' %} </li>
                    <li> {% trans 'Your password can’t be entirely numeric.' %} </li>
                </ul>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/profile/public.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% block style %}
<link rel="stylesheet" href="{% static 'css/books.css'%}">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
{% endblock %}
{% block content %}
    <div id='outer-wrapper'>
    <div class='row' id='content-wrapper'>
    <div class='content-topic contetn-settings'>
    <!-- Main Wrapper -->
    <div id='main-wrapper'>
    <div class='main section' id='main' name='Main Posts'><div class='widget Blog' data-version='2' id='Blog1'>
    <div class='blog-posts hfeed item-post-wrap'>
    <div class='blog-post hentry item-post'>
    <div class='post-content-wrap mb-3'>
    <div class='post-header'>
    <h1 class='post-title'>
        {% trans 'Privacy' %}
    <small>({% trans 'Control who can see your information' %})</small>
    </h1>
    </div>
    <div class='post-body post-content'>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div>
                <li class="checklist-entry list-group-item flex-column align-items-start py-4 px-4">
                    <div class="checklist-item checklist-item-info">
                        <div class="checklist-info">
                            <h5 class="checklist-title mb-0 h4">{% trans 'Email' %}</h5>
                            <spam class="sans">{{user.email}}</spam>
                        </div>
                        <div>
                            <div class="custom-control custom-checkbox custom-checkbox-info">
                                <input class="custom-control-input" type="checkbox" name="email" id="id_email" value='{{form.email}}'  {% if user.public.email %}checked{% endif %} >
                                <label class="custom-control-label" for="id_email"><i class="fas fa-globe-africa"></i></label>
                            </div>
                        </div>
                    </div>
                </li>
               {% if user.profile.phone %}
                <li class="checklist-entry list-group-item flex-column align-items-start py-4 px-4">
                    <div class="checklist-item checklist-item-info">
                        <div class="checklist-info">
                            <h5 class="checklist-title mb-0 h4">{% trans 'Phone' %}</h5>
                            <span class="sans">{{user.profile.phone}}</span>
                        </div>
                        <div>
                            <div class="custom-control custom-checkbox custom-checkbox-info">
                                <input class=" custom-control-input" type="checkbox" name="phone" id="id_phone" value='{{form.phone}}' {% if user.public.phone %}checked{% endif %}>
                                <label class=" custom-control-label" for="id_phone"><i class="fas fa-globe-africa"></i></label>
                            </div>
                        </div>
                    </div>
                </li>
                {% endif %}
                {% if user.profile.web %}
                <li class="checklist-entry list-group-item flex-column align-items-start py-4 px-4">
                    <div class="checklist-item checklist-item-info">
                        <div class="checklist-info">
                            <h5 class="checklist-title mb-0 h4">{% trans 'Website' %}</h5>
                            <a target="_blnck" class="sans" href="https://{{user.profile.web}}"> {{user.profile.web}}</a>
                        </div>
                        <div>
                            <div class="custom-control custom-checkbox custom-checkbox-info">
                                <input class="custom-control-input" type="checkbox" name="web" id="id_web" value='{{form.web}}' {% if user.public.web %}checked{% endif %}>
                                <label class="custom-control-label" for="id_web"><i class="fas fa-globe-africa"></i></label>
                            </div>
                        </div>
                    </div>
                </li>
                {% endif %}
                {% if user.profile.bip %}
                <li class="checklist-entry list-group-item flex-column align-items-start py-4 px-4">
                    <div class="checklist-item checklist-item-info">
                        <div class="checklist-info">
                            <h5 class="checklist-title mb-0 h4">{% trans 'Bio' %}</h5>
                            <span class="lang">{{user.profile.bio}}</span>
                        </div>
                        <div>
                            <div class="custom-control custom-checkbox custom-checkbox-info">
                                <input class="custom-control-input" type="checkbox" name="bio" id="id_bio" value='{{form.bio}}' {% if user.public.bio %}checked{% endif %}>
                                <label class="custom-control-label" for="id_bio"><i class="fas fa-globe-africa"></i></label>
                            </div>
                        </div>
                    </div>
                </li>
                {% endif %}
                {% if user.profile.gander %}
                <li class="checklist-entry list-group-item flex-column align-items-start py-4 px-4">
                    <div class="checklist-item checklist-item-info">
                        <div class="checklist-info">
                            <h5 class="checklist-title mb-0 h4">{% trans 'Gender' %}</h5>
                            <span class="lang">{{user.profile.gander}}</span>
                        </div>
                        <div>
                            <div class="custom-control custom-checkbox custom-checkbox-info">
                                <input class="custom-control-input" type="checkbox" name="gander" id="id_gander" value='{{form.gander}}' {% if user.public.gander %}checked{% endif %}>
                                <label class="custom-control-label" for="id_gander"><i class="fas fa-globe-africa"></i></label>
                            </div>
                        </div>
                    </div>
                </li>
                {% endif %}
                <li class="checklist-entry list-group-item flex-column align-items-start py-4 px-4">
                    <div class="checklist-item checklist-item-info">
                        <div class="checklist-info">
                            <h5 class="checklist-title mb-0 h4">{% trans 'Friends' %}</h5>
                            <span class="sans">{{user.profile.follow.count}}</span>
                        </div>
                        <div>
                            <div class="custom-control custom-checkbox custom-checkbox-info">
                                <input class="custom-control-input" type="checkbox" name="{% trans 'friends' %}" id="id_friends" value='{{form.friends}}' {% if user.public.friends %}checked{% endif %}>
                                <label class="custom-control-label" for="id_friends"><i class="fas fa-globe-africa"></i></label>
                            </div>
                        </div>
                    </div>
                </li>
                {% if user.profile.country %}
                <li class="checklist-entry list-group-item flex-column align-items-start py-4 px-4">
                    <div class="checklist-item checklist-item-info">
                        <div class="checklist-info">
                            <h5 class="checklist-title mb-0 h4">{% trans 'Country' %}</h5>
                            <span class="lang">{{user.profile.country}}</span>
                        </div>
                        <div>
                            <div class="custom-control custom-checkbox custom-checkbox-info">
                                <input class="custom-control-input" type="checkbox" name="country" id="id_country" value='{{form.country}}' {% if user.public.country %}checked{% endif %}>
                                <label class="custom-control-label" for="id_country"><i class="fas fa-globe-africa"></i></label>
                            </div>
                        </div>
                    </div>
                </li>
                {% endif %}
                {% if user.profile.birth %}
                <li class="checklist-entry list-group-item flex-column align-items-start py-4 px-4">
                    <div class="checklist-item checklist-item-info">
                        <div class="checklist-info">
                            <h5 class="checklist-title mb-0 h4">{% trans 'Birth' %}</h5>
                            <small class="sans">{{user.profile.birth}}</small>
                        </div>
                        <div>
                            <div class="custom-control custom-checkbox custom-checkbox-info">
                                <input class="custom-control-input" type="checkbox" name="birth" id="id_birth" value='{{form.birth}}' {% if user.public.birth %}checked{% endif %}>
                                <label class="custom-control-label" for="id_birth"><i class="fas fa-globe-africa"></i></label>
                            </div>
                        </div>
                    </div>
                </li>
                {% endif %}
                <li class="checklist-entry list-group-item flex-column align-items-start py-4 px-4">
                    <div class="checklist-item checklist-item-info">
                        <div class="checklist-info">
                            <h5 class="checklist-title mb-0 h4">{% trans 'Join Date' %}</h5>
                            <span class="sans">{{ user.profile.created|time:"H:i"}} / {{user.profile.created| date:"d/n/Y"}}</span>
                        </div>
                        <div>
                            <div class="custom-control custom-checkbox custom-checkbox-info">
                                <input class="custom-control-input" type="checkbox" name="created" id="id_created" value='{{form.created}}' {% if user.public.created %}checked{% endif %}>
                                <label class="custom-control-label" for="id_created"><i class="fas fa-globe-africa"></i></label>
                            </div>
                        </div>
                    </div>
                </li>
            </ul> 
        </div>
            <input type="submit" class="btn-post2 border p-2 pr-3 pl-3 w-75 m-3 text-center" value="{% trans 'Save' %}">
        </form>
    </div>
    </div>

    </div>
    </div>
    </div></div>
    </div>
    <!-- Sidebar Wrapper -->
    {% include 'sidbar/settings.html'%}
    {% include 'footer/footer.html' %}     
    </div>
    </div>
    </div>
{% endblock %}

users/templates/profile/test.html
<!DOCTYPE html>
<html>
<body>
    <h1 style="color: red;">You have new viewr</h1>
<img src="" alt="">
</body>
</html>

users/templates/profile/update_profile.html
{% extends 'dash.html' %}
{% load static %}
{% load i18n %}
{% block content %}
<div class="row d-flex justify-content-center">
  <div class="col-xl-6 order-xl-1 card">
    <h3 class="p-1 text-center">{% trans 'Update Profile' %}</h3>
    <form method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      <!-- Avatar -->
      <div class="d-flex d-flex justify-content-center ">
        <div class="rounded-circle border overflow-hidden" style="width: 70px; height: 70px;">
          <img width="100%" height="100%" class="cover" src="{{page.avatar.url}}" alt="{{user.username}}">
        </div>
      </div>
      <div class="justify-content-center d-flex">
        <h1 class="h6 text-center">{{page.user.first_name}} {{page.user.last_name}}</h1>
      </div>
      <!-- Avatar -->
      <div class="m-2">
        <label for="id_avatar">{% trans 'Avatar' %}</label>
        <input type="file" name="avatar" value="{{page.avatar}}" id="id_avatar" accept="image/*" class="border form-control">
        {% if page.avatar %}
        <a href="/media/{{page.avatar}}">Current image</a>
        {% endif %}
      </div>
      <!-- Phone -->
      <div class="m-2">
        <label for="id_phone">{% trans 'Phone' %}</label>
        <input type="tel" name="phone" value="{{page.phone}}" id="id_phone" class="border form-control"
          placeholder="{% trans 'Phone' %}...">
      </div>
      <!-- Country -->
      <div class="m-2">
        <span> {% trans 'Country' %}</span>
        <input type="text" name="country" value="{{page.country}}" class="border form-control"
          placeholder="{% trans 'Country' %}...">
      </div>
      <div class="m-2">
        <input type="submit" class="btn-success btn w-100 mt-2" value="{% trans 'Update' %}">

        <div class=" mt-2 ">
          <a class="text-primary text-sm" href="{% url 'change_password' %}">{% trans 'Change Password' %}</a>
        </div>
      </div>
    </form>
    

  </div>
</div>


{% endblock %}

users/templates/profile/user_update_info.html
{% extends 'dash.html' %}
{% load static %}
{% load i18n %}

{% block content %}
    <div class="row d-flex justify-content-center">
        <div class="col-md-6">
            <h1 class="text-center bold h4">{% trans 'Change Contact information' %}</h1>
            <div class='post-body post-content pt-0'>
                <form method="POST" class="p-lg-4 p-xl-4 p-sm-0 p-md-4">
                    {% if confirm %}
                    <div class="alert alert-success p-1" role="alert">
                        <span class="alert-text"><strong>{% trans 'Success!' %}</strong> {% trans 'Info has been updated successfully...' %}</span>
                    </div>
                    {% endif %}
                        {% csrf_token %}
                        <label for="id_username">{% trans 'Username' %}</label>
                        <small class="text-red text-right">{{ form.username.errors }}</small>
                        <input class="form-control border" type="text" name="username" value="{{form.username.value}}" maxlength="150" required id="id_username">
                        <span class="helptext text-primary ">{% trans 'Username should not contain spaces' %}.</span><br><br>
                
                        <label for="id_first_name">{% trans 'First name' %}</label>
                        <small class="text-red text-right">{{ form.first_name.errors }}</small>
                        <input class="form-control border" type="text" name="first_name" value="{{form.first_name.value}}" maxlength="50" required id="id_first_name">
                
                        <label for="id_last_name">{% trans 'Last name' %}</label>
                        <small class="text-red text-right">{{ form.last_name.errors }}</small>
                        <input class="form-control border" type="text" name="last_name" value="{{form.last_name.value}}" maxlength="50" required id="id_last_name">
                
                        <label for="id_email">{% trans 'Email' %}</label>
                        <small class="text-red text-right">{{ form.email.errors }}</small>
                        <input class="form-control border" type="email" name="email" value="{{form.email.value}}" required id="id_email">
                        <input class="btn-success btn mt-3 w-100" type="submit" value="{% trans 'Update' %}">
                    </form>
                  <br>
                <div>
                    {% trans 'Make sure that your contact information is correct and real, so that we can recover your account if you encounter a problem logging in.' %}</div>
            </div>
        </div>
    </div>

{% endblock %}