algo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
from django.conf.urls.static import static
from django_summernote import urls as summernote_urls

urlpatterns = [
    path("i18n/", include("django.conf.urls.i18n")),

]


urlpatterns += i18n_patterns (
    path('admin/', admin.site.urls),
    path('', include('product.urls')),
    path('', include('users.urls')),
    path('summernote/', include('django_summernote.urls')),
    

)


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path
from .views import *



urlpatterns = [
    path('', home, name='home'),
    path('dash', dashboard, name='dashboard'),
    path('product/list', products),
    path('product/create', createProduct),
    path('product/delete/<int:id>', deleteProduct),
    path('product/update/<int:id>', updateProduct),
    path('product/<int:pk>', ProductDetail),
    path('add-to-cart', AdToCart),
    path('cart', cart),
    path('contact', contact),
    path('contact/list', contactList),
    path('contact/<int:id>', message),
    path('products', ourProducts),
    path('benefit/create', createBenefit),
    path('benefit/update/<int:pk>', benefitUpdate),
    path('benefit/list', listBenefit),
    path('benefit/delete/<int:pk>', benefitDelete),

    # Articl
    path('post/create', PostCreate),
    path('post/list', PostList),
    path('post/update/<int:pk>', PostUpdate),
    path('post/delete/<int:pk>', PostDelete),
    path('post/<int:pk>', PostDetail),

    # 
    path('thanks', thanks),



    # Orders
    path("order/all", OrderList),
    path("order/confirmed", OrderConfirmed),
    path("order/canceled", OrderCanceled),
    path("order/cancel", CancelOrder),
    path("order/confirm", ConfirmOrder),
    path("order/new", OrderNew),
    path('order/<int:pk>', order),
    path('costumer/list', costumers)
]

product/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone



class Category(models.Model):
    name = models.CharField(max_length=300)

    def __str__(self):
        return self.name

class Language(models.Model):
    language = models.CharField(("Langue"), max_length=50)
    code = models.CharField(("Code"), max_length=50)

    def __str__(self):
        return self.language



class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(("Title"), max_length=200)
    image = models.ImageField(upload_to='postImage')
    description = models.TextField()
    body = models.TextField()
    language = models.ForeignKey(Language, on_delete=models.CASCADE, null=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)



    def __str__(self):
        return self.title
    

class Product(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=300)
    image = models.ImageField(upload_to='images')
    price = models.IntegerField(default=0)
    old_price = models.IntegerField(null=True, blank=True)
    cart = models.ManyToManyField(User, blank=True, related_name="user_cart")
    description = models.TextField()
    body = models.TextField()
    language = models.ForeignKey(Language, on_delete=models.CASCADE, null=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True, blank=True)
    slug = models.SlugField(null=True, blank=True)
    code = models.TextField(null=True, blank=True)
    created = models.DateTimeField(auto_now=False, auto_now_add=True)

    def __str__(self):
        return self.name



class Contact(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    full_name = models.CharField(max_length=300, blank=True, null=True)
    email = models.EmailField(max_length=300, blank=True, null=True)
    message = models.TextField()
    phone = models.CharField(default='', max_length=30)
    is_read = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.email
    


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    full_name = models.CharField(max_length=300, blank=True, null=True)
    email = models.EmailField(max_length=300, blank=True, null=True)
    phone = models.CharField(max_length=20, blank=True, null=True)
    products = models.ManyToManyField(Product, related_name='product_order')
    payment = models.CharField(max_length=100)
    confirmed = models.BooleanField(default=False)
    canceled = models.BooleanField(default=False)
    is_payed = models.BooleanField(default=False)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True,blank=True, null=True)




class Benefit(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=500)
    description = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True, blank=True)
    language = models.ForeignKey(Language, on_delete=models.CASCADE, null=True, blank=True)


    def __str__(self):
        return self.title

product/forms.py
from django import forms
from . models import *
from django.utils.translation import gettext as _
from django_summernote.widgets import SummernoteWidget

class ProductForm(forms.ModelForm):
    body = forms.CharField(widget=SummernoteWidget())
    class Meta:
        model = Product
        fields = ['name', 'image', 'price', 'old_price', 'description', 'body', 'language', 'category', 'code']
        widgets = {
            'description': forms.Textarea(attrs={'rows': 5}),
            'language': forms.Select(attrs={'class': 'form-select'}),
            'category': forms.Select(attrs={'class': 'form-select'}),
        }




class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['full_name', 'email', 'message', 'phone']
        widgets = {
            'full_name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'message': forms.Textarea(attrs={'class': 'form-control'}),
        }



class BenefitForm(forms.ModelForm):
    class Meta:
        model = Benefit
        fields = ['title', 'description', 'language', 'category']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'required': True}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'rows': 3, 'required': True}),
            'language': forms.Select(attrs={'class': 'form-select'}),
            'category': forms.Select(attrs={'class': 'form-select'}),
        }



class PostForm(forms.ModelForm):
    body = forms.CharField(widget=SummernoteWidget())
    class Meta:
        model = Post
        fields = ['title', 'image', 'description', 'body', 'language', 'category']
        widgets = {
            'language': forms.Select(attrs={'class': 'form-select'}),
            'category': forms.Select(attrs={'class': 'form-select'}),
        }

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['full_name', 'email', 'phone', 'payment']

product/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import Paginator
from . models import *
from .forms import *
from django.contrib import messages
from django.utils.translation import activate, gettext as _
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse

now = timezone.now()


def home(request):
    algo_benefits = Benefit.objects.filter(language__code=request.LANGUAGE_CODE, category__name='Algo Indicateur').order_by('-created')[0:10]
    robot_benefits = Benefit.objects.filter(language__code=request.LANGUAGE_CODE, category__name='Robot Auto trading').order_by('-created')[0:10]


    products_indicateur = Product.objects.filter(language__code=request.LANGUAGE_CODE, category__name="Algo Indicateur").order_by('-created')
    products_robot = Product.objects.filter(language__code=request.LANGUAGE_CODE, category__name="Robot Auto trading").order_by('-created')

    post_indicateur = Post.objects.filter(language__code=request.LANGUAGE_CODE, category__name="Algo Indicateur").order_by('-created')
    post_robo = Post.objects.filter(language__code=request.LANGUAGE_CODE, category__name="Robot Auto trading").order_by('-created')

    context = {
        'algo_benefits': algo_benefits,
        'robot_benefits':  robot_benefits,
        
        'products_indicateur': products_indicateur,
        'products_robot': products_robot,

        'post_indicateur': post_indicateur,
        'post_robo': post_robo,
       
    }
    return render(request, 'index.html', context)

@login_required
def dashboard(request):
    products = Product.objects.all().order_by('-created')
    users = User.objects.all()
    

    today_oders = Order.objects.filter(created__date=now.date())
    month_orders = Order.objects.filter(created__year=now.year, created__month=now.month)


    orders = Order.objects.filter(canceled=False, confirmed=False).order_by('-created')


    context = {
        'products': products,
        'users': users,
        "today_oders": today_oders,
        "month_orders": month_orders,
        'orders': orders
    }
    return render(request, 'dash/index.html', context)



# Product Admin
def products(request):
    list = Product.objects.all().order_by('-created')
    paginator = Paginator(list, 25) # Show 25 contacts per page.

    page_number = request.GET.get('page')
    products = paginator.get_page(page_number)

    context = {
        'products': products
    }
    return render(request, 'dash/product-list.html', context)

def ProductDetail(request, pk):
    product = get_object_or_404(Product, pk=pk)
    form = OrderForm(request.POST or None)
    if request.method == "POST":
        order = form.save(commit=False)
        if request.user.is_authenticated:
            order.user = request.user
        order.save()
        order.products.add(product)
        order.save()
        return redirect('/thanks')
    context = {
        'product': product
    }
    return render(request, 'product.html', context)


# Create Product
@login_required
def createProduct(request):
    form = ProductForm()
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid:
            obj = form.save(commit=False)
            obj.user = request.user
            obj.save()
            messages.success(request, _("Produit créé avec succès!"))
            return redirect('/product/create')
    context = {
        'form': form
    }
    return render(request, 'dash/product-create.html', context)




@login_required
def deleteProduct(request, id):
    if request.user.is_authenticated:
        product = get_object_or_404(Product, id=id)
        product.delete()
        messages.success(request, _('Le produit a été supprimé avec succès.'))
    else :
        return redirect('/')
    return redirect('/product/list')

@login_required
def updateProduct(request, id):
    product = get_object_or_404(Product, id=id)

    form = ProductForm(instance=product)
    if request.method == 'POST':
        form = ProductForm(request.POST,request.FILES, instance=product)
        if form.is_valid:
            form.save()
            messages.success(request, _("Produit mis à jour avec succès"))
            return redirect('/product/list')
    context = {
        'product': product,
        'form': form
    }
    return render(request, 'dash/product-create.html', context)

@login_required
def AdToCart(request):
    id = request.GET.get('product')
    product = get_object_or_404(Product, id=id)
    if request.user in product.cart.all():
        product.cart.remove(request.user)
        cart = False
    else:
        product.cart.add(request.user)
        cart = True
    product.save()
    return JsonResponse({"cart": request.user.user_cart.all().count(), 'exist': cart})

@login_required
def cart(request):
    products = Product.objects.filter(cart__in=[request.user])
    form = OrderForm(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            order = form.save(commit=False)
            order.user = request.user
            if products.count() > 0:
                order.save()
                for item in products:
                    order.products.add(item)
                    item.cart.remove(request.user)
                form.save_m2m()
                return redirect('/thanks')
            else :
                messages.success(request, _("Vous n'avez pas de produit dans le panier"))
                return redirect('/cart')

    context = {
        'products': products,
        'form': form
    }
    return render(request, 'cart.html', context)



def thanks(request):
    return render(request, 'thanks.html')



def contact(request):
    form = ContactForm(request.POST or None)
    if form.is_valid():
        contact = form.save(commit=False)
        if request.user.is_authenticated:
            contact.user = request.user
        contact.save()
        messages.success(request, _("Le message a été envoyé avec succès"))
        return redirect('/contact')

    context = {
        'form': form,
        "title": _("Contactez-nous")
    } 
    return render(request, 'contact.html', context)

@login_required
def contactList(request):
    list = Contact.objects.all().order_by('-created')
    paginator = Paginator(list, 30) # Show 25 contacts per page.

    page_number = request.GET.get('page')
    contacts = paginator.get_page(page_number)
    context = {
        'msgs': contacts
    }
    return render(request, 'dash/contact-list.html', context)


@login_required
def message(request, id):
    message = get_object_or_404(Contact, id=id)
    message.is_read = True
    message.save()
    context = {
        'message': message
    }
    return render(request, 'dash/message.html', context)




def ourProducts(request):
    list = Product.objects.filter(language__code=request.LANGUAGE_CODE).order_by('-created')
    paginator = Paginator(list, 25) # Show 25 contacts per page.

    page_number = request.GET.get('page')
    products = paginator.get_page(page_number)
    context = {
        'products': products
    }
    return render(request, 'products.html', context)

@login_required
def listBenefit(request):
    list = Benefit.objects.all().order_by('-created')
    paginator = Paginator(list, 25) # Show 25 contacts per page.

    page_number = request.GET.get('page')
    benefits = paginator.get_page(page_number)
    return render(request, 'dash/benefit-list.html', {'benefits': benefits})


@login_required
def createBenefit(request):
    if request.method == 'POST':
        form = BenefitForm(request.POST)
        if form.is_valid():
            benefit = form.save(commit=False)
            benefit.user = request.user
            benefit.save()
            messages.success(request, "Avantage a été créé avec succès." )
            return redirect('/benefit/create')
    else:
        form = BenefitForm()
    return render(request, 'dash/benefit-from.html', {'form': form})


@login_required
def benefitUpdate(request, pk):
    benefit = get_object_or_404(Benefit, pk=pk)
    if request.method == 'POST':
        form = BenefitForm(request.POST, instance=benefit)
        if form.is_valid():
            benefit = form.save()
            messages.success(request, "Avantage a été edit avec succès." )
            return redirect('/benefit/list')
    else:
        form = BenefitForm(instance=benefit)
    return render(request, 'dash/benefit-from.html', {'form': form})


@login_required
def benefitDelete(request, pk):
    benefit = get_object_or_404(Benefit, pk=pk)
    if request.user.is_superuser:
        benefit.delete()
        messages.success(request, "L'avantage a été supprimé avec succès." )
        return redirect('/benefit/list')
    else :
        return redirect('/')

# Articl





@login_required
def PostCreate(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            messages.success(request, _("Article créé avec succès."))
            return redirect('/post/list')
    else:
        form = PostForm()
    
    context = {'form': form, 'title': 'Create Article'}
    return render(request, 'dash/post/create.html', context)


@login_required
def PostList(request):
    list = Post.objects.all().order_by('-created')
    paginator = Paginator(list, 30) # Show 25 contacts per page.

    page_number = request.GET.get('page')
    posts = paginator.get_page(page_number)
    context = {'posts': posts}
    return render(request, 'dash/post/list.html', context)

@login_required
def PostUpdate(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():

product/templates/dash/benefit-from.html
{% extends 'dash.html' %}


{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="card col-md-10">
            <h1 class="h2 mt-2">Create Benefit</h1>
            <div class="card-body py-3">
                {% if messages %}
                {% for message in messages %}
                <div {% if message.tags %} class="alert alert-{{ message.tags }} p-2" {% endif %}>{{ message }}</div>
                {% endfor %}
                {% endif %}
                <form method="POST">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="title" class="form-label"><strong>Title</strong></label>
                        <input type="text" value="{% if form.title.value %}{{form.title.value}}  {% endif %}"
                            class="form-control" id="title" name="title" required>
                    </div>
                    <div class="mb-3">
                        <label for="old_price" class="form-label mt-2">Language:</label>
                        {{form.language}}
                    </div>
                    <div class="mb-3">
                        <label for="description" class="form-label"><strong>Description</strong></label>
                        <textarea class="form-control" id="description" name="description" rows="3" required>
                            {% if form.description.value %}{{form.description.value}}  {% endif %}
                        </textarea>
                    </div>

                    <div class="mb-3">
                        <label for="category" class="form-label"><strong>Category</strong></label>
                        {{ form.category }}
                    </div>
                    <button type="Create" class="btn btn-primary w-100 rounded-pill">Create</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

product/templates/dash/benefit-list.html
{% extends 'dash.html' %}


{% block content %}

<div class="container">
    <div class="row justify-content-center">
        <div class="card">
            <div class="card-body">
              <h5 class="card-title">All Benefits</h5>

              <!-- List group with Advanced Contents -->
              {% if messages %}
                {% for message in messages %}
                <div {% if message.tags %} class="alert alert-{{ message.tags }} p-2" {% endif %}>{{ message }}</div>
                {% endfor %}
               {% endif %}
              <ul class="list-group">
                {% for benefit in benefits %}
                <li href="#" class="list-group-item list-group-item-action">
                    <div class="d-flex w-100 justify-content-between">
                      <h5 class="mb-1"><strong>{{benefit.title}}</strong></h5>
                      <small class="text-muted">{{benefit.created}}</small>
                    </div>
                    <p class="mb-1">{{benefit.description}}</p>
                    <a href="/benefit/update/{{benefit.id}}" class="btn btn-success btn-sm">Update</a>
                    <a onclick="return confirm('Are you sure you want to delete benefit.')" class="btn btn-danger btn-sm" href="/benefit/delete/{{benefit.id}}">Delete</a>
                </li>
                {% empty %}
                <h3 class="text-center">No Benefit</h3>
                {% endfor %}
              </ul><!-- End List group Advanced Content -->

            </div>
          </div>
    </div>
</div>
{% endblock content %}

product/templates/dash/contact-list.html
{% extends 'dash.html' %}
{% load i18n %}

{% block content %}

<div class="container">
    <div class="row justify-content-center">
        <div class="card col-md-10">
            <div class="card-body">
              <h5 class="card-title">All Messages</h5>
              <!-- List group with Advanced Contents -->
              <div class="list-group">
                {% for contact  in msgs  %}
                <a href="/contact/{{contact.id}}" class="list-group-item list-group-item-action {% if not contact.is_read %}active{% endif %} border-bottom" aria-current="true">
                    <div class="d-flex w-100 justify-content-between">
                      <h5 class="mb-1" dir="auto">{{ contact.full_name }} </h5>
                      <small>{{ contact.created|timesince }}</small>
                    </div>
                    <p dir="auto" class="mb-1">{{ contact.message|truncatechars:100}}</p>
                  </a>
                {% empty %}
                <h3 class="text-center">{% trans "No Messages" %}</h3>
                {% endfor %}
              </div><!-- End List group Advanced Content -->

            </div>
            <div class="pagination mb-3 d-flex justify-content-center">
                <span class="step-links">
                    {% if msgs.has_previous %}
                        <a class="btn btn-outline-primary rounded-pill" href="?page={{ msgs.previous_page_number }}">Previous</a>
                    {% endif %}
                    {% if msgs.has_next %}
                        <a class="btn btn-outline-primary rounded-pill" href="?page={{ msgs.next_page_number }}">Next</a>
                    {% endif %}
                </span>
            </div>
          </div>
    </div>
</div>
{% endblock content %}

product/templates/dash/message.html
{% extends 'dash.html' %}


{% block content %}

<div class="container">
    <div class="row justify-content-center">
        <div class="card col-md-10">
            <div class="card-body">
                <div class="text-center mt-3">
                    {% if message.user %}
                    <img src="{{ message.user.profile.avatar.url }}" width="60px" alt="{{message.full_name}}" class="rounded-circle border">
                     {% else %}   
                     <img src="/media/user_default.webp" width="60px" alt="{{message.full_name}}" class="rounded-circle border">

                    {% endif %} 
                    <h5 class="card-title p-1">{{message.full_name}}</h5>
                    {% if message.user %}
                    <h6>@{{message.user.username}}</h6>
                    {% endif %}
                </div>
                <p>Email <strong>&#xa0;<a href="mailto:{{message.email}}">{{message.email}}</a></strong></p>
                {% if message.phone %}
                <p>Phone <strong>&#xa0;&#xa0;<a href="tel:{{message.phone}}">{{message.phone}}</a></strong>
                    &#xa0;&#xa0;<a target="_blank" href="https://api.whatsapp.com/send?phone={{message.phone}}&text=Bonjour" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-original-title="Whatsapp message"><i class="bx bxl-whatsapp fs-5"></i></a>
                </p>
                {% endif %}
                <pre dir="auto" class="h6" style="white-space: pre-wrap;font-family: system-ui;overflow: inherit;">{{message.message}}</pre>
                <hr />
                <p dir="auto">{{ message.created|timesince }}</p>
                
            </div>
          </div>
    </div>
</div>
{% endblock content %}

product/templates/dash/product-create.html
{% extends 'dash.html' %}


{% block content %}
<div class="row d-flex justify-content-center">
    <div class="col-md-8 card border p-2 shadow-none">
        <h1 class="h2">Create Product</h1>
        {% if messages %}
            {% for message in messages %}
            <div {% if message.tags %} class="alert alert-{{ message.tags }} p-2" {% endif %}>{{ message }}</div>
            {% endfor %}
        {% endif %}
        <form method="POST" enctype="multipart/form-data" class="row g-3">
            {% csrf_token %}
            <div class="col-md-6">
                <label for="name" class="form-label">Product Name:</label>
                <input type="text" value="{{product.name}}" name="name" class="form-control" required>
            </div>

            <div class="col-md-6">
                <label for="image" class="form-label">Product Image:</label>
                <input type="file" name="image" class="form-control" accept="image/*">
                {% if product.image %}
                    <a href="{{product.image.url}}">Current Image</a>
                {% endif %}
            </div>

            <div class="col-md-6">
                <label for="price" class="form-label">Price:</label>
                <input type="number" value="{{product.price}}" name="price" class="form-control" required>
            </div>

            <div class="col-md-6">
                <label for="old_price" class="form-label">Old price:</label>
                <input type="number" value="{{product.old_price}}" name="old_price" class="form-control">
            </div>

            <div class="col-md-6">
                <label for="language" class="form-label">Language:</label>
                {{form.language}}
            </div>
            <div class="col-md-6">
                <label for="Category" class="form-label">Category:</label>
                {{form.category}}
            </div>

            <div class="col-md-12">
                <label for="code">Paypal Code</label>
                <textarea class="form-control mt-2" placeholder="Paypal Code..." name="code" cols="40" rows="5" required="" id="id_description"  spellcheck="false">{{product.code}}</textarea>
         </div>
            <div class="col-md-12">
                <label for="description" class="form-label">Description:</label>
                <textarea name="description" rows="6" class="form-control" required>{{product.description}}</textarea>
            </div>

            <div class="col-md-12">
                <label for="description" class="form-label">Description:</label>
                {{form.body}}
            </div>

            <div class="col-md-12">
                <button type="submit" class="btn btn-primary w-100">Create</button>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

product/templates/dash/product-list.html
{% extends 'dash.html' %}
{% load static %}
{% block content %}
<div class="row">
    <div class="col-12">
        <div class="card top-selling overflow-auto">
          <div class="card-body pb-0">
            <h5 class="card-title">All Products</h5>
            {% if messages %}
                {% for message in messages %}
                <div {% if message.tags %} class="alert alert-{{ message.tags }} p-2" {% endif %}>{{ message }}</div>
                {% endfor %}
            {% endif %}
            <table class="table table-borderless">
              <thead class="bg-light">
                <tr>
                  <th scope="col">Preview</th>
                  <th scope="col">Product</th>
                  <th scope="col">Price</th>
                  <th scope="col">Orders</th>
                  <th scope="col">Actions</th>
                </tr>
              </thead>
              <tbody>
               {% for product in products %}
                <tr>
                  <th scope="row"><a href="{{ product.image.url }}"><img width="50px" src="{{ product.image.url }}" alt=""></a></th>
                  <td><a href="/product/{{product.id}}" class="text-primary fw-bold">{{product.name}}</a></td>
                  <td>{{product.price}} MAD</td>
                  <td class="fw-bold">{{product.product_order.all.count}}</td>
                  <td>
                    <a class="btn btn-sm btn-success" href="/product/update/{{product.id}}"><i class="bx bxs-pen"></i></a>

                    <a class="btn btn-sm btn-danger" href="/product/delete/{{product.id}}" onclick="return confirm('Are you sure you want to delete Product')"><i class="bx bxs-trash"></i></a>
                  </td>
                </tr>

                {% empty %}
                <div class="text-cetner">
                    <h3 class="text-center">No Products</h3>
                </div>
                {% endfor %}
              </tbody>
            </table>
    
          </div>
    
        </div>
      </div>
</div>


{% endblock content %}